### ISSUE TITLE
Issue in sending proto msgs

### ISSUE THREAD

**Issue by RanGojo** [cosmos/snap#26]
Hi, 

I was trying to integrate cosmos-snap and faced some issues in sending transacations.  (Sign is successful but send is failing)

When I'm sending amino message without proto using snap api, I face with this error:

![Screenshot from 2023-11-19 14-07-11](https://github.com/cosmos/snap/assets/99180934/ab7e8599-9bcc-4b20-ab2b-7a20d359a136)

Also, when I sign proto msgs and send that to the snap, I face with this one: (It seems it is ignoring my proto messages and looking for msgs field) I've same code for my keplr wallet and it works fine.

![Screenshot from 2023-11-19 14-34-58](https://github.com/cosmos/snap/assets/99180934/9f3afe1a-d740-4372-a4e4-5341f8041f40)

Is it a bug / limitation on cosmos snap?

**Comment by schnetzlerjoe** [comment]
> Hi, 
> 
> I was trying to integrate cosmos-snap and faced some issues in sending transacations.  (Sign is successful but send is failing)
> 
> When I'm sending amino message without proto using snap api, I face with this error:
> 
> ![Screenshot from 2023-11-19 14-07-11](https://github.com/cosmos/snap/assets/99180934/ab7e8599-9bcc-4b20-ab2b-7a20d359a136)
> 
> Also, when I sign proto msgs and send that to the snap, I face with this one: (It seems it is ignoring my proto messages and looking for msgs field) I've same code for my keplr wallet and it works fine.
> 
> ![Screenshot from 2023-11-19 14-34-58](https://github.com/cosmos/snap/assets/99180934/9f3afe1a-d740-4372-a4e4-5341f8041f40)
> 
> Is it a bug / limitation on cosmos snap?

This looks like a potential parsing Amino for display issue. Can you share the message you are sending?

**Comment by schnetzlerjoe** [comment]
@RanGojo I am closing this since we have not heard back If you are still running into problems reopen or send in another issue! 

PS: Using @cosmsnap/snapper with getOfflineSigner might also help here.

Thanks!
