### ISSUE TITLE
Add signArbitrary support

### ISSUE THREAD

**Issue by HS-Joe** [cosmos/snap#27]
Currently the snap supports only signDirect and signAmino.
Many dApps rely on proving ownership of a wallet for their internal logic, it would be great to add support for this.

**Comment by schnetzlerjoe** [comment]
> Currently the snap supports only signDirect and signAmino.
> Many dApps rely on proving ownership of a wallet for their internal logic, it would be great to add support for this.

We will add this ASAP in upcoming release!

**Comment by schnetzlerjoe** [comment]
This was added to https://www.npmjs.com/package/@cosmsnap/snapper a few months ago! Let us know if you run into anyissues. `window.cosmos.signArbitrary`
