### ISSUE TITLE
Cosmos Extension for MetaMask doesn't work anymore

### ISSUE THREAD

**Issue by Remzi1993** [cosmos/snap#33]
The Cosmos Extension for MetaMask doesn't work anymore. I installed the Snap from here: https://snaps.metamask.io/snap/npm/cosmsnap/snap/
![image](https://github.com/cosmos/snap/assets/980950/3668994f-8a89-47be-b96b-a6faf6dce086)

And I try to continue on this website: https://metamask.mysticlabs.xyz/ but everything seems to be not working for me.
![Screenshot 2024-02-27 003232](https://github.com/cosmos/snap/assets/980950/075153e1-c7dd-4faf-85be-974991eaf3a4)

I checked in MetaMask of the Snap was installed and enabled, see below:
![Screenshot 2024-02-27 003255](https://github.com/cosmos/snap/assets/980950/18c4599a-ee3f-41f2-afc4-287adcc93cc2)

**Specs:**
Chrome version: Version 122.0.6261.70 (Official Build) (64-bit)
MetaMask extension version: 11.10.0 (updated on 19 February 2024)

**Comment by Remzi1993** [comment]
I also get the following error if I click on the extension on the Snaps download website:
![Screenshot 2024-02-27 004440](https://github.com/cosmos/snap/assets/980950/ad84398f-4bc0-4790-9c47-0d0d0599f5ef)

**Comment by Remzi1993** [comment]
**The extensions works, but I can't see the Cosmos network, see:**
![Screenshot 2024-02-28 200112](https://github.com/cosmos/snap/assets/980950/908c387a-40c9-42da-8eb8-f8c9591adf5c)

**Can't add it either:**
![Screenshot 2024-02-28 200223](https://github.com/cosmos/snap/assets/980950/49f6237c-30fd-4ccb-b9ca-bc889b048679)

**Comment by schnetzlerjoe** [comment]
this is for integration/code issues. if you are having issues with the Snap as a wallet user please reach out to support! help@mysticlabs.xyz
